service: anonymous-sender
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs16.x
  stage: sd-dev
  region: ap-south-1
  architecture: x86_64
  versionFunctions: false
  endpointType: REGIONAL

functions:
  getMessages:
    description: "Returns all messages received for a particular user"
    handler: ./routes/messages/GET/index.handler
    tags:
      API PATH: GET /messages
    events:
      - httpApi:
          path: /messages
          method: get
  deleteMessages:
    description: "Deletes a particular message by its ID"
    handler: ./routes/messages/DELETE/index.handler
    tags:
      API PATH: DELETE /messages/:messageId
    events:
      - httpApi:
          path: /messages/{messageId}
          method: delete
  postMessages:
    description: "Add a message for a particular user"
    handler: ./routes/messages/POST/index.handler
    tags:
      API PATH: POST /messages
    events:
      - httpApi:
          path: /messages
          method: post
  getUsers:
    description: "Returns data for a particular user"
    handler: ./routes/users/GET/index.handler
    tags:
      API PATH: GET /users/:userId
    events:
      - httpApi:
          path: /users/{userId}
          method: get
  postUsersRegister:
    description: "Handles registration of new users"
    handler: ./routes/users/register/POST/index.handler
    tags:
      API PATH: POST /users/register
    events:
      - httpApi:
          path: /users/register
          method: post
  postUsersLogin:
    description: "Handles user login"
    handler: ./routes/users/login/POST/index.handler
    tags:
      API PATH: POST /users/login
    events:
      - httpApi:
          path: /users/login
          method: post
  getUsersRefresh:
    description: "Refreshes user authentication token"
    handler: ./routes/users/refresh/GET/index.handler
    tags:
      API PATH: GET /users/refresh
    events:
      - httpApi:
          path: /users/refresh
          method: get
  getUsersLogout:
    description: "Handles user logout"
    handler: ./routes/users/logout/GET/index.handler
    tags:
      API PATH: GET /users/logout
    events:
      - httpApi:
          path: /users/logout
          method: get
